### ISSUE TITLE
Update to Bootstrap 5.3.3

### ISSUE THREAD

**Issue by janscarton** [concrete5/bedrock#329]
Any reason Bootstrap is [pinned to 5.2.3 in package.json](https://github.com/concretecms/bedrock/blob/1.4.x/package.json#L22)? There shouldn't be any breaking changes between 5.2.3 and 5.3.3 (latest).

**Comment by aembler** [comment]
We want to be pretty deliberate with when we adopt new versions of Bootstrap, since with Bedrock we're promising that it will support all the blocks in the core, Dashboard pages in the core, etc... We are looking into adopting Bootstrap 5.3 soon, likely in 9.3.

**Comment by janscarton** [comment]
Thanks Andrew. Dark Mode and custom color themes are the nicest [changes](https://blog.getbootstrap.com/2023/05/30/bootstrap-5-3-0/) in Bootstrap 5.3 imho. We're sideloading it into our bedrock theme sites now. We haven't run into any problems so far. Will let you know if any surface.
