### ISSUE TITLE
onSelect : function(nodes) of concreteTree not work in 9.3.2, she works on 9.2.8

### ISSUE THREAD

**Issue by 6tematik** [concrete5/bedrock#345]
Hello,

Since the Concrete update to 9.3.2, it is no longer possible to select an element from a concretreTree.
For example, in dashboard/users/search/edit, it is no longer possible to select the root folder.
We think the error comes from the bedrock/assets/cms/js/tree.js file. But there is no error returned.

![Capture d’écran du 2024-07-29 14-37-20](https://github.com/user-attachments/assets/10d808f2-1af4-434e-bea4-7a068d093c5f)

We do not have the problem on a project in version 9.2.8.

Thanks in advance.
Sincerely.

**Comment by aembler** [comment]
I just tried this with the latest 9.3.3 and was able to select a sub-folder as well as the root file manager folder. This may be related to some fixes that hissy just put into place.
